version: '3.3'
services:
  web:
    image: picroc/express-app
    build: . # build from Dockerfile
    command: npm start # command to start container
    volumes:
      - .:/code
    ports: # expose ports to host from container
      - "3000:3000" # host : container
    links:
      - redis
  redis:
    image: "redis"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
volumes:
  db_data: {} # define volumes (virtual "disks")